name: Updating Web App
run-name: ${{ github.actor }} is updating the Web App 🚀
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - '*'
jobs:
  build:
    name: Update Web App
    runs-on: ubuntu-latest
    steps:

    - name: Checkout main
      uses: actions/checkout@v4.1.1

    - name: Write SSH key to file
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.KEY }}" > ~/.ssh/id_ed25519
        cd ~
        pwd
        cd -
        pwd
        ls -dl ~/.ssh
        chmod 600 ~/.ssh
        ls -dl ~/.ssh

    - name: Add server to known hosts
      run: (ssh-keyscan -H ${{ secrets.HOST }} 2> /dev/null) | grep ed25519 >> ~/.ssh/known_hosts

    - name: Sync newest changes to cloud server
      run: |
        rsync -avzn --delete \
          . ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/flask-app
    
#    - name: Copy files into cloud server
#      uses: appleboy/scp-action@v0.1.4
#      with:
#        host:  ${{ secrets.HOST }}
#        username: ${{ secrets.USERNAME }}
#        key: ${{ secrets.KEY }}
#        source: "."
#        target: /var/www/flask-app      
